backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
show_preview_link: true
display_url: https://lutas.netlify.com
collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    sort: "date:desc"
    fields:
      - {label: "Título", name: "title", widget: "string", required: true}
      - {label: Resumo 164-220, name: summary, widget: text, required: true, pattern: ['.{164,220}', "Deve ser entre 164 e 220 caracteres"]}
      - {label: "Texto", name: "body", widget: "markdown", required: true}
      - {label: "Imagem", name: "thumbnail", widget: "image", required: false}
      - {label: "Autor(es)", name: "author", widget: "relation", required: true, collection: "autores", searchFields: ["name"], valueField: "name", multiple: true, displayFields: ["name"]}
      - {label: "Data de Postagem no Site", name: "date", widget: "datetime", required: true}
      - {label: "Data de Atualização", name: "update", widget: "datetime", required: false}
  - name: "livros"
    label: "Livros"
    folder: "content/livros"
    create: true
    slug: "{{slug}}"
    sort: "publish_date:desc"
    fields:
      - {label: "Título", name: "title", widget: "string", required: true}
      - {label: Resumo 164-220, name: summary, widget: text, required: true, pattern: ['.{164,220}', "Deve ser entre 164 e 220 caracteres"]}
      - {label: "Descrição", name: "body", widget: "markdown", required: true}
      - {label: "Capa", name: "cover", widget: "image", required: true}
      - {label: "Autor(es)", name: "author", widget: "relation", required: true, collection: "autores", searchFields: ["name"], valueField: "name", multiple: true, displayFields: ["name"]}
      - {label: "Data de Lançamento", name: "release_date", widget: "datetime", required: true}
      - {label: "Preço", name: "price", widget: "number", required: true, valueType: "float"}
      - {label: "Data de Postagem no Site", name: "publish_date", widget: "datetime", required: true}
  - name: "autores"
    label: "Autores"
    folder: "content/autores"
    create: true
    slug: "{{slug}}"
    sort: "date:desc"
    fields:
      - {label: "Nome", name: "name", widget: "string", required: true}
      - {label: "Descrição", name: "title", widget: "string", required: false, hint: "Pequena descrição do autor: Prof., Dr., etc"}
      - {label: "Biografia", name: "body", widget: "markdown", required: true}
      - {label: "Email", name: "email", widget: "email", required: false}
      - {label: "Site", name: "url", widget: "string", required: false}
      - {label: "Data de Criação", name: "date", widget: "datetime", required: true}
  - name: "eventos"
    label: "Eventos"
    folder: "content/eventos"
    create: true
    slug: "{{slug}}"
    sort: "date:desc"
    fields:
      - {label: "Tipo", name: "type", widget: "string", required: true, hint: "Tipo de evento"}
      - {label: "Nome", name: "title", widget: "string", required: true}
      - {label: "Data & Hora", name: "date", widget: "datetime", required: true, dateFormat: "DD.MM.YY", timeFormat: "HH:mm"}
      - {label: "Local", name: "venue", widget: "string", required: true}
      - {label: "Site", name: "url", widget: "string", required: false, hint: Site do local ou do evento.}
      - {label: "Resumo", name: summary, widget: text, required: true}
      - {label: "Descrição", name: "body", widget: "markdown", required: true}
      - {label: "Imagem", name: "thumbnail", widget: "image", required: false}
      - {label: "Data de Postagem no Site", name: "publish_date", widget: "datetime", required: true}
